### ISSUE TITLE
AliOssServiceProvider 里的日志debug能去掉吗

### ISSUE THREAD

**Issue by yooha** [summergeorge/Aliyun-oss-storage#1]
![image](https://user-images.githubusercontent.com/14746323/51235140-b9453a00-19a9-11e9-9a3c-410b96c435f9.png)

**Comment by summergeorge** [comment]
<img width="1035" alt="wx20190215-140117 2x" src="https://user-images.githubusercontent.com/5298923/52837648-8d44e200-312a-11e9-83be-879588c2d6a9.png">

这个配置项是用来控制 debug 日志开启状态的。
