### ISSUE TITLE
SignUrl give http even ssl is set to true

### ISSUE THREAD

**Issue by afiqiqmal** [summergeorge/Aliyun-oss-storage#11]
![Screenshot 2020-03-25 at 5 10 22 PM](https://user-images.githubusercontent.com/9051312/77520028-848d1680-6ebb-11ea-9dad-e0eba78ee206.png)

for `url()` give https but not `signUrl`
![Screenshot 2020-03-25 at 5 11 29 PM](https://user-images.githubusercontent.com/9051312/77520218-d5047400-6ebb-11ea-9b49-405425d694d5.png)

**Comment by jasonfish568** [comment]
What we did was replacing the http part to https as we found it was so complicated when using different buckets

**Comment by afiqiqmal** [comment]
Im just create a helper to change the ssl

```
    function ssl_url($url)
    {
        if (config('app.force_https')) {
            return preg_replace("/^http:/i", "https:", $url);
        }

        return $url;
    }

   ssl_url(Storage::disk()->url());
```

**Comment by summergeorge** [comment]
@afiqiqmal 欢迎提交PR，Thank you！
