### ISSUE TITLE
使用自定义域名   'isCName' => true, 就报错

### ISSUE THREAD

**Issue by gyp719** [summergeorge/Aliyun-oss-storage#2]
使用自定义域名   'isCName' => true, 就报错 ，使用 oss  分配的域名 可以正常运行，  但是 我用自定义的 域名 链接 去访问 图片 也可以进行访问， 自定义域名 不清楚是什么情况？？

![image](https://user-images.githubusercontent.com/30563368/57905216-5b1d5a80-78a8-11e9-92c3-b193d322eaae.png)

**Comment by summergeorge** [comment]
验证了一下，没有出现你说的问题：
配置项举例：
![image](https://user-images.githubusercontent.com/5298923/57922574-9e8cbe80-78d2-11e9-8f11-5672b9e61710.png)
调用：
![image](https://user-images.githubusercontent.com/5298923/57922620-bbc18d00-78d2-11e9-8c44-9a342cae7e41.png)
结果：
![image](https://user-images.githubusercontent.com/5298923/57922645-c845e580-78d2-11e9-82a8-6a07720eb202.png)
