### ISSUE TITLE
为什么新增加了signUrl接口，不直接支持laravel原有的temporaryUrl呢？

### ISSUE THREAD

**Issue by ZacharyJia** [summergeorge/Aliyun-oss-storage#3]
功能应该是一致的吧，都是生成一个带签名的临时URL。

**Comment by jasonfish568** [comment]
所以现在这个signUrl是可以正常使用的吗？这个repo是summergeorge从jacobcyl的原repo fork出来的，其实都是在原基础上改进的，如果有熟悉Laravel Filesystem的可以提交个PR

**Comment by ZacharyJia** [comment]
@txlife 
现在的SignUrl应该是能用的。这两个作者目前都不怎么积极吧，好久都没有更新了，我在这个项目里提的PR也没有回应。目前我的那个fork里是按照目前的SignUrl实现了一个temporaryUrl接口的。

**Comment by summergeorge** [comment]
#4 已经增加，version:2.1.4
